
// // LOGIN TYPES ==============================
// export const LOGIN_DATA_START = "LOGIN_DATA_START"
// export const LOGIN_GET_COMPANY_DATA = "LOGIN_GET_COMPANY_DATA"
// export const LOGIN_DATA_END = "LOGIN_DATA_END"



// // HR OPERATIONS ===> FAMILY TYPES
// export const GET_TRANSITION_FAMILY_DATA = "GET_TRANSITION_FAMILY_DATA";
// export const GET_TRANSITION_FAMILY_START = "GET_TRANSITION_FAMILY_START";
// export const GET_TRANSITION_FAMILY_DATA_SINGLE = "GET_TRANSITION_FAMILY_DATA_SINGLE";
// export const GET_TRANSITION_FAMILY_END = "GET_TRANSITION_FAMILY_END";
